
login_check:
    pattern:  /login_check

logout:
    pattern:  /logout

miit_app:
    resource: "@MiitAppBundle/Controller"
    type:     annotation

miit_frontend:
    resource: "@MiitFrontendBundle/Controller"
    type:     annotation