
login_check:
    pattern:  /login_check

logout:
    pattern:  /logout

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

miit_app:
    resource: "@MiitAppBundle/Controller"
    type:     annotation
    prefix:   /app

miit_frontend:
    resource: "@MiitFrontendBundle/Controller"
    type:     annotation