# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


    miit.api.oauth.realtime_extension:
        class: Miit\ApiBundle\OAuth\BingoGrantExtension
        tags:
            - { name: fos_oauth_server.grant_extension, uri: 'realtime_type' }